language: node_js
node_js:
  - "5"
  - "6"
  - "stable"
sudo: false
before_script:
  - npm install -g gulp
  - npm install
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
