sudo: false
language: node_js
node_js:
#  - "5"
  - "6"
#  - "7"

cache:
  yarn: true

addons:
  code_climate:
    repo_token: $REPO_TOKEN

#script: "gulp coverage"

after_success:
  - codeclimate-test-reporter < lcov.info
