environment:
  matrix:
  - nodejs_version: "Stable"
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - npm --version
  - yarn run build:client:dev
  - yarn run build:client:prod

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off