environment:
  matrix:
  - nodejs_version: "Stable"
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install yarn
  - yarn install

test_script:
  - node --version
  - npm --version
  - yarn run build:client:dev
  - yarn run build:client:prod

build: off